CpanelInc/addon_securityadvisor

- pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm
Use the algorithms employed elsewhere on a cPanel system to determine the kernel version is the latest installed version.
> Corrected kernel version detection

- pkg/Cpanel/Security/Advisor/Assessors/Apache.pm
Case 189717: Some users starting with "cpanel", along with a variety of
other system users, were being listed as uncaged, even though that's
expected and desired.  Caging those users might cause the respective
software not to work properly.  Skip these reserved users when checking
as they do not represent a security risk.
> Don't warn about uncaged reserved users

- pkg/Cpanel/Security/Advisor/Assessors/Mysql.pm
Case STS-358: By default MySQL will listen on all addresses. We should
check for this, and issue a warning in Security Advisor. This check will
inspect the value of 'bind-address' in '/etc/my.cnf'. A basic check will
also be made of iptables rules present. If bind-address is set to a
non-localhost value and there are no iptables reject/deny rules in place
for the MySQL port, then a warning will be issued.
> Add warning when MySQL is listening on a public address.

- pkg/Cpanel/Security/Advisor/Assessors/Mysql.pm
Case CPANEL-5699: An error message would appear in the cPanel error log
when running the MySQL test because the command to check for anonymous
users failed.  Since that failure is desirable behavior (as it means the
system is secure), add an option to silence that output.  With a
corresponding change in 11.58, this allows us to not log errors in this
particular case.
> Avoid logging error messages in MySQL test.

- pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm
With KernelCare by CloudLinux, it's possible that yum won't be aware that the effective running version of the kernel has changed from when the server was last restarted.
The changes suggested here check for the presence of "/usr/bin/kcarectl" to verify whether KernelCare is installed, then take the output of "/usr/bin/kcarectl --uname", shave off the "+" sign on the end, and allow that to be compared to the output from yum. Only if yum produces results that don't match the KernelCare kernel version does the "kernel_updates" subroutine produce any output.
Later in the script, if there's a KernelCare kernel version reported, its value replaces that of the running kernel version before the running kernel version is reported to the end user.
> Support for KernelCare

- pkg/Cpanel/Security/Advisor.pm
> Add POD for advise types and propse change to the notifications

- pkg/Cpanel/Security/Advisor/Assessors/Brute.pm
Previously the module just checked to see if the csf directory was present.
Added the ability to check whether csf was disabled, and if lfd was running.
> Detection of csf and lfd state

- pkg/Cpanel/Security/Advisor/Assessors/Mysql.pm
Previously this module only checked for iptables rules that would deny the
mysql port, however by default csf denies all ports, and then allows only
those specified in the configuration, so the rules it's looking for would not
be present. In addition to the check against iptables, I added a check to see
if the csf.conf file exists, and whether or not the mysql port is open. Also,
I modified the suggestions to recommend either changing the bind address OR
closing the port.
> Mysql.pm - Check CSF Ports

- pkg/Cpanel/Security/Advisor/Assessors/Trojans.pm
Modify Trojans.pm to use same checks that SSP uses
Add note that if RPM database is corrupted, libkey check may be a false positive.
> Updated Trojans.pm to version 1.04

- pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm
Case SWAT-22: Added a check to see if KC is installed, if not provide
and "info" advisory with a link to the KernelCare site for
buying/installing.
> Promote KernelCare if not installed.

- pkg/Cpanel/Security/Advisor/Assessors/Scgiwrap.pm
Case CPANEL-7731: The cPanel EA 4 suexec binary uses capabilities, but CloudLinux's uses the setuid bit.  Detect both cases properly.
> Detect CloudLinux's EA 4 suexec binary.

- pkg/Cpanel/Security/Advisor/Assessors/Apache.pm
Case EA-5542:
In the WHM Security Advisor page, the advisory concerning the Bluehost
Symlink protection contains a go link pointing back to the EA3 pages
describing the Symlink Race Condition Protection.
This documentation is updated for EA4, and a new web page exists to
describe the Symlink Race Condition Protection as it applies to EA4.
This commit udpates the go link (for EA4 systems only) to point to the
matching EA4 go link.
> Doc link to Symlink Race Condition Protection updated for EA4.

- pkg/Cpanel/Security/Advisor/Assessors/Apache.pm
Case CPANEL-9923: Use systemd to check cagefs status, when available.
> Use systemd to check cagefs status when available.

- pkg/Cpanel/Security/Advisor/Assessors/Jail.pm
Case ZC-2347: A new module was introduced in 11.60,
Cpanel/PwCache/Build.pm but older versions do not have this change.
Added a conditional to load the correct one for the correct versions.
> Can't locate Cpanel/PwCache/Build.pm in Security Advisor < 11.60

- pkg/templates/main.tmpl
Case CPANEL-11502: Updating Security Advisor page to use master.tmpl wrapper
starting version 63.
> Updated main.tmpl to use wrapper based on version

- pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm
Case SWAT-22, SWAT-320: Added a check to see if KC is installed, if not
provide an "info" advisory with a link to the KernelCare site for
buying/installing.
The decision whether or not to show the info advisory is based on three
criteria:
* If KC is already installed, don't bother.
* If we're in an environment that *can't* use KC, don't bother.
* If the partner for this server has decreed that "thou shalt not,"
then don't. If they've listed an alternative path for that--via
another website or email address, show it, but use that link instead.
SWAT-320: A couple of changes were suggested in review.  Minor
matters..Found a few minor perltidy issues.
Link to install page if KC license is found, but not installed.
Case SWAT-359: Check to see if there is a valid KernelCare license
and and the …
>     Promote KernelCare if not installed on cPanel 11.64 and greater.

- CONTRIBUTING.md
- pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm
CPANEL-11799: It is desirable to block the automated script from
sending notifications that may look too spammy. Add an attribute
to allow for this behavior.
> Create new attribute to block notification

- pkg/Cpanel/Security/Advisor/Assessors/Apache.pm
- pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm
- pkg/Cpanel/Security/Advisor/Assessors/Symlinks.pm
> Add Security Advisor detection support for KernelCare's free tier.

- pkg/Cpanel/Security/Advisor/Assessors/Processes.pm
Case CPANEL-16976: Since systemd isn't present on CentOS 6, don't suggest using systemctl.  Also, strip off the ".service" suffix in the UI, since that won't be useful there, either.
This has been tested on both CentOS 6 and 7 and it produces the right thing in both cases.
> Avoid recommending systemctl on CentOS 6

- pkg/Cpanel/Security/Advisor/Assessors/Symlinks.pm
Case  CPANEL-17590: Turned out that the check for the cP hardened kernel
was useless and saying that any kernel with symlink protection,
including CloudLinux, was the cPKernel. Fixed this by directly checking
the kernel returned by uname. There is no dependent cPanel change required
for this to work.
Work done in SWAT-850 via parent, SWAT-839.
> Fixed broken check for cPKernel (cPanel's hardened kernel).

- pkg/cgi/addon_securityadvisor.cgi
Reverts CpanelInc/addon_securityadvisor#80
> Revert "Disable addon_securityadvisor.cgi on dnsonly servers"

- pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm
> Do not suggest kernelcare when system is already licensed for kernelcare

- pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm
- pkg/Cpanel/Security/Advisor/Assessors/Jail.pm
- pkg/templates/main.tmpl
- t/pkg-Cpanel-Security-Advisor-Assessors-Imunify360.t
- Add Imunify360 to the Security Advisor.
- Update Security Advisor CSS styles.
- Update Jail.pm to work better with the new styles.
Merge task: LC-10502.
> LC-10417: Add Imunify360 to Security Advisor.

- pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm
- t/pkg-Cpanel-Security-Advisor-Assessors-Imunify360.t
LC-10523: This is a squash of the changes from the LC-10506 story branch.
The majority of the changes were made on the cPanel & WHM side. These are
just minor adjustments to accommodate the changing interface of the
module.
> Security Advisor changes to support Store purchase refactor.

- pkg/Cpanel/Security/Advisor/Assessors/Brute.pm
Case CPANEL-28312: Updated the link provided for enabling cPHulk.
Changelog: Updated URL for enabling cPHulk during brute force protection
check.
> Update link URL for enabling cPHulk.

- pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm
installed.
Case BWG-1413
Refactor things a bit also.
> Add advice to install ImunifyAV+ if the user has a license but it is not

- pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm
Case BWG-1501
Users will now be able to install ImunifyAV free even when partners have
disabled ImunifyAV+ in manage2.
Changelog:
> Allow ImunifyAV install when ImunifyAV+ is disabled.

- pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm
- pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm
BWG-1406
Update the SA with product upsell changes. Mainly changing the upsells to blue info boxes instead of yellow recommendations.
Also a tidy of Kernel.pm.
> Iavp update

- pkg/Cpanel/Security/Advisor/Assessors/PHP.pm
Case CPANEL-31835: Improve PHP EOL phrasing and update interface links
to open in a new tab.
Changelog:
> Improve PHP EOL phrasing

- pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm
Case CPANEL-26846: KernelCare is not currently compatible with Secure
Boot, so we need to detect Secure Boot and include a message about
it instead of the KernelCare notice.
Also deleting some old code meant for unsupported older cPanel &
WHM versions that should not have been left in place.
Team-Story: BWG_1585
Team-Task: BWG-1586
Team-Merge-Task: BWG-1588
> Add awareness of Secure Boot to Kernel.pm.

- pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm
Case CPANEL-32560: Rearrange existing code so that the suggestion to
install KernelCare when it is licensed actually works.
> Fix suggestion to install KernelCare when licensed

- pkg/Cpanel/Security/Advisor/Assessors/Apache.pm
Case CPANEL-35012:
* Security Advisor could advise to install mod_ruid2 when
* LiteSpeed is running in order to jail apache processes.  This is bad
* advice since LiteSpeed is not compatible with mod_ruid2
* Update the advise to only recommend CageFS on CloudLinux instead
Changelog:  Do not advise to install mod_ruid2 with LiteSpeed
> Do not advise to install mod_ruid2 with LiteSpeed

- pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm
Case CPANEL-37744:  In CPANEL-37720, the
Whostmgr::Imunify360::needs_kernelcare was updated to use Cpanel::OS to
determine the OS distro and version.  It now returns appropriately for
the supported OSs.  In order to keep our code as dry as possible, we
should use that method and remove the _needs_kernelcare and _server_type
subs from Imunify360 Assessor in Security Advisor.
Changelog:
> Teach Imunify360 check about Whostmgr::Imunify360::needs_kernelcare

- pkg/Cpanel/Security/Advisor/Assessors/Processes.pm
> Corrected typo in Cpanel::Sys::OS::Check namespace.
