CpanelInc/addon_securityadvisor

pkg/Cpanel/Security/Advisor/Assessors/Apache.pm
pkg/Cpanel/Security/Advisor/Assessors/Scgiwrap.pm

The hard coded paths to suexec incorrect under ea4 causing errouneous failures.
In the same file I noticed hard coded httpd path too so updated that one also.
See HB-412 for details on testing and 2 more ea4 related tasks (didn't want to to get too scopey).

Support ea4 suexec

---

pkg/Cpanel/Security/Advisor/Assessors/Processes.pm

Case 192065: CentOS 6+ comes with the needs-restarting executable, which
identifies any processes that are running with outdated binaries (execs or
libs).  These processes must be restarted before they can benefit from the
updates.  Since these updates may contain security fixes, let the admin
know about them in the Security Advisor.

Add check for running processes that are outdated

---

pkg/Cpanel/Security/Advisor/Assessors.pm

Case CPANEL-3865: The CloudLinux kernel's lve module changed its name to
kmodlve.  Look for either one of these module names.
Note that querying /etc/redhat-release is not enough to determine
whether the kernel is a CloudLinux kernel, since it's possible to run
CloudLinux on a CentOS kernel, which can happen (usually by accident) in
some configurations.

Fix detection of CloudLinux kernels.

---

pkg/Cpanel/Security/Advisor/Assessors/Jail.pm

This prevents the tool cobra is working on from sending a
notification every night even when nothing has changed.

Always notify unjailed users in the same order

---

pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm

On LXC containers, as with Virtuozzo, the kernel is under control
of the host. Warning about kernel being out of date is not helpful.

Don't check for kernel updates on LXC

---

pkg/Cpanel/Security/Advisor/Assessors/Processes.pm

Case CPANEL-6077: Don't run the outdated process check on systems
without smaps support (grsec kernels).

Don't run outdated process check on systems without smaps support.

---

pkg/Cpanel/Security/Advisor/Assessors/Scgiwrap.pm

JIRA CPANEL-4783 renames the setuid scgiwrap binary to
scgiwrap_deprecated in 11.58, so this changes the appropriate security
advisor test.

deprecate scgiwrap in 11.58

---

pkg/Cpanel/Security/Advisor/Assessors/SSH.pm

without-password password option as an alternate to no
in case they still need to use keys.

Update advise for the SSH advisor to recommend the

---

pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm

KernelCare version 2.5-4 apparently doesn't include the processor architecture
in the "kcarectl --uname" output. This change should accommodate both.

Accommodate KernelCare output change

---

pkg/Cpanel/Security/Advisor.pm

Case CPANEL-6109: There are two ways for an assessor module to provide
advice: call a method on the security advisor object, or call a method
on $self that wraps the method on the security advisor object.  If the
latter case occurred, the lookup for the function which called us would
always produce something in the Cpanel::Security::Advisor::Assessors
package.
The right way to solve this would be to inspect the class of the $self
object whose method called us, but that isn't possible.  Instead, look
for a specific module pattern either 1 or 3 steps back (to ignore the 2
levels of helper functions) and take that as the module name.

Ensure module names are correctly displayed.

---

pkg/Cpanel/Security/Advisor/Assessors/Permissions.pm

It was trying to sprintf the array of expected values into
the string rather than the elements of the expected values.

Corrected missprint of expected value for file permissions

---

pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm

Case SWAT-22: Augmented earlier change (59410f93fef) from this
case to look at the company id. If it is cPanel, offer Go link
to purchase KernelCare. If it is not, suggest user contact their
hosting provider.

Display KernelCare suggestion based on company id.

---

pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm

Case SWAT-121: Reverting KernelCare suggestion for now until
we are ready to make this advisor more widely available. Below
are the revert details:
Revert "Display KernelCare suggestion based on company id."
This reverts commit 75470e10643aa3bb2fefb1df59582d7f6986e759.
Revert "Promote KernelCare if not installed."
This reverts commit 59410f93fefb37983a52f43a66cfe60f3be1108d.

Revert the Kernel Care promotion from Security Advisor.

---

pkg/Cpanel/Security/Advisor.pm
pkg/Cpanel/Security/Advisor/Assessors/Apache.pm
pkg/Cpanel/Security/Advisor/Assessors/Brute.pm
pkg/Cpanel/Security/Advisor/Assessors/ClamAV.pm
pkg/Cpanel/Security/Advisor/Assessors/EntropyChat.pm
pkg/Cpanel/Security/Advisor/Assessors/Frontpage.pm
pkg/Cpanel/Security/Advisor/Assessors/Iptables.pm
pkg/Cpanel/Security/Advisor/Assessors/Jail.pm
pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm
pkg/Cpanel/Security/Advisor/Assessors/Mysql.pm
pkg/Cpanel/Security/Advisor/Assessors/Passwords.pm
pkg/Cpanel/Security/Advisor/Assessors/Processes.pm
pkg/Cpanel/Security/Advisor/Assessors/SSH.pm
pkg/Cpanel/Security/Advisor/Assessors/Scgiwrap.pm
pkg/Cpanel/Security/Advisor/Assessors/Spam.pm

This commit adds static keys. They are preceded by the assessor's name (e.g., SSH_ for SSH.pm). There is a bikeshed alert here. I think that while there should be some candid discussion on what the initial set of keys should be, we should not spent much time at all. These and future keys must be globally unique. They will be used to track messages sent, this work is being done internally via SWAT-94.

Added preliminary message keys.

---

pkg/Cpanel/Security/Advisor.pm

I also took the opportunity to encapsulate look ups both ways in subroutines.  _lookup_advise_type is used in the latest change in SWAT-94.

Fixed warning being thrown about cplint about unused variables.

---

pkg/Cpanel/Security/Advisor/Assessors/Jail.pm

Case CPANEL-8328:  The fetch_pwcache() function had been
moved do a different module.

Fixed the Jail Assessor

---

CONTRIBUTING.md
README.md

Case SWAT-96: Documenting for contributors the require of message
keys for all advice messages and how to determine a good one.
Doc reviewed via DOCPRO-412.

Documenting information about static keys for contributors.

---

pkg/Cpanel/Security/Advisor/Assessors/Apache.pm
pkg/Cpanel/Security/Advisor/Assessors/Symlinks.pm

Case SWAT-102: Adding kernel-level symlink detection support to SA,
picking up where GS left off.
This work was originally done in Case NO-668;  includes probe for GID
for which symlink protections apply, ensure symlink enforcement is actually
enabled as another failsave.
This commit also represents a squash of f5ccb3e and f74caba.

Adding kernel-level symlink protection detection.

---

pkg/Cpanel/Security/Advisor/Assessors/Apache.pm
pkg/Cpanel/Security/Advisor/Assessors/Symlinks.pm

Fix the symlink protection message to be grammatical and provide a link to the documentation.  Also, address some broken links.

Improve symlink protection message

---

pkg/Cpanel/Security/Advisor/Assessors/Trojans.pm

Case CPANEL-9301: The previous go.cpanel.net link didn't point anywhere
useful.  Point the link to a useful documentation page.

Use proper go.cpanel.net link for compromised systems.

---

pkg/Cpanel/Security/Advisor/Assessors/Apache.pm
pkg/Cpanel/Security/Advisor/Assessors/Symlinks.pm

Case CPANEL-10169:
In a previous fix, we added an EA4 specific go-link for the
symlink race condition description page, but we only added it for
the Bluehost symlink patch advisory.  This commit updates all the other
advisories to also use the EA4 page, if the system is an EA4 system.

Fix symlink race condition links to point to EA4, if appropriate.

---

pkg/Cpanel/Security/Advisor/Assessors/Apache.pm

On a grsec kernel, if the sysctl option was not enabled, cPanel would indicate that the setting was incorrectly set. This occurred because the word "unknown" was being printed on standard
error, but we only looked for it on standard output.  Capture the error output as well, so we correctly detect when the option is not enabled.
I tested this by forcing the code to think it was a grsec kernel and then running the Security Advisor on a CentOS 6 system.  After this change, it indicates that it's a warning, instead of an error.

Properly detect sysctl setting on grsec kernel

---

pkg/Cpanel/Security/Advisor/Assessors/Apache.pm
pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm

Case CPANEL-10580: Made the check to see if cagefs was running use
a regex as the Reporter had suggested. Also decoupled the check
for unprotected users from the check to see if cagefs was running
because this hid the run check bug if any users were unprotected by
cagefs.
Cleaned comments in Kernel.pm, nothing functional.
Work done via SWAT-330.

_is_cagefs_check was reporting a false negative, fixed it.

---

pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm

CPANEL-11794: We don't want to offer KernelCare on Amazon Cloud
servers. So, block that.

Prevent offering KernelCare on Amazon Cloud

---

pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm

Any value that is passed in via a _# parameter in maketext() will be
displayed verbatim, without any translation.  Avoid passing in strings
that we know can be translated.

Correctly mark KernelCare strings for translation

---

pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm
t/lib/Test/Assessor.pm
t/pkg-Cpanel-Security-Advisor-Assessors-Kernel.t

This builds on the changes CPANEL-12259 and aims to deduplicate the logic and to generally consume small bits of technical debt.

Rework Kernel assessor to use Cpanel module

---

pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm
t/pkg-Cpanel-Security-Advisor-Assessors-Kernel.t
t/pkg-Cpanel-Security-Advisor-Assessors-Kernel_advertisements.t

This builds on the changes CPANEL-12308 and aims to deduplicate the logic and to generally consume small bits of technical debt.

Rework Kernel assessor to use Cpanel module for KernelCare advertisements

---

pkg/Cpanel/Security/Advisor/Assessors/Processes.pm
t/lib/Test/Assessor.pm
t/pkg-Cpanel-Security-Advisor-Assessors-Processes.t

Case PIG-2858: To encourage re-use, the logic to check for outdated
processes was copied to cPanel & WHM.  It was also improved to further
encourage adoption.  Modify this assessor to use the new module to gain
these improvements.
This change requires CPANEL-12242, which is merged into v66.

Rework Processes assessor to use Cpanel module

---

pkg/Cpanel/Security/Advisor/Assessors/Mysql.pm

Case CPANEL-16551:
Previously the mysql command offered to drop the anonymous user
would fail if there were multiple anonymous users, mapped to
different hosts.
This command avoid the problematic "drop user" syntax which doesn't
work well with multiple users, as the db engine expands the host
to '%', and then the drop user syntax fails because it does not
handle the wildcard for the host properly in a fully qualified
database user name specification.
The solution is to just delete the users with a where statement,
and then flush the pprivileges to ensure correct security state.
This will also trigger cascade deletes of grants the user had
before it was deleted.

Replace MySQL command to drop anonymous users with one that works.

---

pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm

Case CPANEL-17735: CL kernel already comes baked in with the symlink
protection patch, so even thought CL is supported by KernelCare, we do
not need to offer the free tier at all.
Work done in subtask SWAT-862, parent case SWAT-838.
Requires changes made to upstream 70 via Case CPANEL-17591.

Don't offer free symlink patch from KC if on CloudLinux

---

pkg/Cpanel/Security/Advisor/Assessors/Usernames.pm

Case STS-620
Usernames that do not conform to cPanel's username validation
requirements will now be alerted in the Security Advisor. This includes
usernames that are reserved because of an email alias and user's that
are in an incomplete state or misconfigured.

Warn users about invalid, reserved, and misconfigured usernames.

---

pkg/Cpanel/Security/Advisor/Assessors/Apache.pm

Case CPANEL-18127: When using the Jail Apache tweak setting, some
features of Mailman are unavailable due to those paths not being mounted
in jailshell.  For the moment, mark this as a known issue in the
Security Advisor so people can make a reasonable decision whether to
enable this setting.

Note that mailman may not work under jailshell

---

pkg/Cpanel/Security/Advisor/Assessors/Apache.pm

Case ZC-3956: EA 3 deprecation message is shown in the security
advisor with details about the date of deprecation and the removal of its support
from cPanel & WHM v78.

Show EA 3 deprecation message

---

pkg/cgi/addon_securityadvisor.cgi

Case CPANEL-18480:
Disable addon_securityadvisor.cgi on dnsonly servers.

Disable addon_securityadvisor.cgi on dnsonly servers

---

pkg/Cpanel/Security/Advisor/Assessors/ClamAV.pm

Case CPANEL-20678: The ClamAV version check is now more tolerant to the
version strings being slightly different but still the same. We now
display the versions that were obtained in the advice block.
If we fail to parse the version, we now give an error advice block. This
could happen in some edge cases, like when the freshclam.conf file is
missing.
The landing page to update ClamAV has been change from
'scripts2/getthemes?modules=1' to 'scripts2/manage_plugins'.

Improve ClamAV version checks.

---

pkg/Cpanel/Security/Advisor/Assessors/Mysql.pm
pkg/Cpanel/Security/Advisor/Assessors/Trojans.pm
pkg/templates/main.tmpl
t/pkg-Cpanel-Security-Advisor-Assessors-Mysql.t

Case CPANEL-25838: Address a couple of minor warnings that were seen in the
error log on a cPanel server.
- The main.tmpl was using the wrong variable to check for the current
version, which would cause an unbalanced comparison warning to show up
in the error log.
- The Trojans.pm module had a couple of checks that no longer existed so
they are now removed.
- Fixed up the error strings in the Mysql module and added a test for
the module.
Changelog: Address some minor warnings

Address some minor warnings

---

pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm

Case CPANEL-25984: We were suggesting that the "Extra" patchset would be
available for download after purchasing KernelCare, regardless of
whether or not the system is compatiable. To avoid this, I've added
logic to only display this message on CentOS 6/7 systems.
Changelog: Only mention KernelCare "Extra" patchset on supported
systems.

Only mention KernelCare's "Extra" patchset on supported systems.

---

pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm
pkg/Cpanel/Security/Advisor/Assessors/SSH.pm

One having to do with doing try {} when eval would be better
Another about calling a dynamic method like a static method

Fix a couple of warnings in securityadvisor (SSH & Kernel modules)

---

pkg/Cpanel/Security/Advisor/Assessors/SSH.pm

Case CPANEL-26566: To resolve an issue with detecting PermitRootLogin,
use correct function for case insensitive access to sshd_config
directives, as values are stored with lowercase key names internally

Use case insensitive sshd_config access functions

---

pkg/Cpanel/Security/Advisor/Assessors/SSH.pm

Case CPANEL-26289: The logic for checking if PermitRootLogin was
implicitly enabled by not being defined was broken. I've resolved this
by using the get_config() accessor to check the currently configured (or
not configured) value.
Changelog: Resolved syntax error in root SSH login check.

Fixed syntax error in logic for checking if root logins are enabled.

---

pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm

In the case where there is a problem with the Imunify360 license,
a deep link into the UI will produce a 404 message rather than
explaining what's actually wrong. This type of license issue should
hopefully never happen outside of a testing environment like ours,
but if it does, the user will get a much more meaningful message
by navigating to the front.
Team-Task: LC-10635
Original-Team-Task: LC_10618
Team-Story: LC_10506

Go to front of Imunify360 instead of deep linking into UI.

---

pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm
t/pkg-Cpanel-Security-Advisor-Assessors-Imunify360.t

Case CPANEL-27631: As part of our v82 work, the Imunify360 assessor
was refactored in a way that it began using a couple of the new
v82-only capabilities of Whostmgr::Store.  This was OK at first
because v80 was not on the latest SA commit from master, but once
it was updated, it began failing.
The fix here is just to revert the changes to the Imunify360 assessor.
It would be nice to have this on the new style, but it's not actually
necessary. Since it needs to be compatible with v80, we don't have
that option.
Changelog: Fix compatibility issue with Security Advisor assessor.

v80 and v82 compatibility for Imunify360 assessor in Security Advisor

---

pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm
t/pkg-Cpanel-Security-Advisor-Assessors-Imunify360.t

Case CPANEL-27727: As part of the fix for CPANEL case 27631, some of our v82
work was reverted. This commit is a resubmission of the custom URL capability
for v82 in a way that is still compatible with versions prior to 82.
Team-Story: LC_10732
Original-Task: LC_10737
Team-Merge-Task: LC-10743

Restore Imunify360 custom URL capability for v82.

---

pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm
t/pkg-Cpanel-Security-Advisor-Assessors-Kernel.t

Case CPANEL-27657: Update the good advice message to mention kernelcare when
kernelcare is installed and up to date.
Changelog: Update good advice message when kernelcare is installed and up to
date

Update good advice message when kernelcare is installed and up to date

---

pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm
pkg/Cpanel/Security/Advisor/Assessors/Kernel.pm

Case CPANEL-29071: RTD-112 is introducing a new Whostmgr13 for banners
specific. This fix will update the proper URL (script 12 or 13)
depending on the new script availability.
This patch needs to merge in sync with Whostmgr13 changes from
CPANEL-29070.
Team Case: RTD_1
Merge Case: RTD-152
Changelog:

Update links to use the new Whostmgr13 script.

---

pkg/Cpanel/Security/Advisor/Assessors/Apache.pm

Case CPANEL-28134: Now that easyapache3 is EOL, we should say so in the
security advisor output.
Changelog: Updated EasyApache3 EOL message to indicate it has gone EOL.

Updated EasyApache3 EOL message to indicate it has gone EOL.

---

pkg/Cpanel/Security/Advisor/Assessors/SSH.pm

Case CPANEL-29466: The link for updating system rpms was incorrect, and
needed to be updated. This commit updates that check to direct the user
to the updatesrvsoftware WHM dialog.
Changelog: Updated the “Update System Software” link.

Updated the “Update System Software” link.

---

pkg/Cpanel/Security/Advisor/Assessors/PHP.pm

Case CPANEL-30562: Add a new security advisor module for PHP
to show a EOL warning in Security Advisor page if EOL versions
of PHP are installed.
Changelog:

Add PHP EOL warning in Security Advisor.

---

pkg/Cpanel/Security/Advisor/Assessors/Apache.pm

Update apache chroot advice to mention ruid2
Case CPANEL-31064: Clarify that mod_ruid2 is needed to implement the
Apache vhost chroot advice.

CPANEL-31064

---

pkg/Cpanel/Security/Advisor/Assessors/ClamAV.pm
pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm

Case BWG-1333
This commit adds the ability to install ImunifyAV and purchase
ImunifyAV+ from the security advisor. It also removes the ClamAV check
from cPanel versions 88 and later and recommends ClamAV be uninstalled
if both ClamAV and ImunifyAV are installed.
Changelog: Update the Security Advisor with ImunifyAV and ImunifyAV+

Update the security advisor with ImunifyAV

---

pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm

Case BWG-1457
If a custom purchase url is set in the users manage2 account for
ImunifyAV+, it should now be used in the Security Advisor upsell.
Otherwise we default to the cpanel store url.
Changelog:

Allow a custom purchase url to be used for ImunifyAV+

---

pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm

Case BWG-1514
It was possible to see the ImunifyAV+ advice when Imunify360 was
installed but not licensed. You will now only see the ImunifyAV+ advice
when Imunify360 is both not installed and not licensed.
Changelog:

Do not show ImunifyAV and AV+ advice when Imunify360 exists.

---

pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm

Case BWG-1514
Two error boxes would show when IAVP was licensed but not installed.
This has been corrected so it will only show the IAVP error and not
the IAV error at the same time.
Changelog:

Show correct errors when IAVP is licensed but not installed.

---

pkg/Cpanel/Security/Advisor/Assessors/Brute.pm

Case CPANEL-31849: Use executability of /usr/sbin/csf instead of
existence of /etc/csf to determine if CSF is installed. Fixes a
false-positive result caused by other software dropping a configuration
file into /etc/csf while it isn't installed.
Changelog: Fix Security Advisor mistakenly detecting that CSF is
installed in some cases.

Fix CSF false-positive installation check

---

pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm

Case BWG-1416
It was possible for false positives to appear in the security advisor
due to people purchasing Imunify360 directly from CloudLinux or another
provider other than cPanel. The license check for Imunify360 will be
removed until SDI has a method in place for us to query the CloudLinux
license servers for the license status.
Changelog:

No longer license check Imunify360

---

pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm
pkg/templates/main.tmpl

Case BWG-1444
If the Imunify product checks return good advice, we now provide a link
to the landing page in WHM along with a link to the Imunify
documentation.
Changelog:

Add links to a landing page and info page when advice is good.

---

pkg/Cpanel/Security/Advisor/Assessors/PHP.pm

Case CPANEL-32266: Update EOL PHP wording to use plurals when there is
more than one EOL PHP version.

Further improve EOL PHP phrasing

---

pkg/Cpanel/Security/Advisor.pm
pkg/Cpanel/Security/Advisor/Assessors.pm
pkg/Cpanel/Security/Advisor/Assessors/_Self.pm
t/pkg-Cpanel-Security-Advisor-Assessors-_Self.t

Case CPANEL-32705: Certain advisors reply upon a functional and accurate
RPM database to give accurate results. If an attempt to fetch the list
of packages exits abnormally, times out, or contains far fewer entries
than expected, raise appropriate advice recommending addressing this
issue. Additionally, modify the run order of assessors so that the new
assessor runs first.

Report conditions leading to inaccurate advice

---

pkg/Cpanel/Security/Advisor.pm
t/lib/Cpanel/Security/Advisor/Assessors/MockAssessor.pm
t/lib/Cpanel/Security/Advisor/Assessors/MockLoadFail.pm
t/lib/Cpanel/Security/Advisor/Assessors/MockNewFail.pm
t/lib/Test/Mock/SecurityAdvisor.pm
t/pkg-Cpanel-Security-Advisor.t

Case CPANEL-33980: Ensure that assessor module load errors are passed
correctly to the advisor output even if the logger clobbers EVAL_ERROR.
Use a better method to search for and load the assessor modules.

Fix module load error reporting

---

pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm

case HB-5789: Tweaks the conditionals a bit to ensure the banners show up properly on CentOS 8. No changes were made to the unit test, as it already is failing.

Don't discount CentOS 8 or higher for Immunify or kcare

---

pkg/Cpanel/Security/Advisor/Assessors.pm
pkg/Cpanel/Security/Advisor/Assessors/Apache.pm
pkg/Cpanel/Security/Advisor/Assessors/Jail.pm

Case CPANEL-35822:
* Previously, the check only ensured that a cagefsctl binary was present
* and executable.  This check is insufficient since cagefs could be
* installed but disabled.  In order to verify that cagefs is properly
* enabled, we now verify that the binary is present, and check to see if
* the cagefs reports as being enabled
Changelog:  Improve check to determine that cagefs is enabled

Improve check to determine that cagefs is enabled

---

pkg/Cpanel/Security/Advisor/Assessors/Apache.pm

Case CPANEL-36090:  Previously, you could dismiss the advise regarding
LiteSpeed by enabling the jailapache setting.  This was incorrect since
LiteSpeed is unaffected by that setting.  Now, the LiteSpeed advise is
processed prior to checking for jailapache in order to ensure that it is
processed regardless of what the jailapache setting is.
Changelog:  Update LiteSpeed advise to not be dependent on jailapache
setting

Update LiteSpeed advise to not be dependent on jailapache setting

---

pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm

case HB-6019: Since the GetOS check is going away in v96, may as well
just use what is there to help us already in the class we just loaded.

Move to using "should offer" from the Imunify360 code

---

pkg/Cpanel/Security/Advisor/Assessors/Jail.pm

Case CPANEL-36311:
Changelog: Fix JailShell checks when CageFS is not enabled.

Fix reversed cagefs logic in jailshell check

---

pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm

Case CPANEL-37594:  Cpanel::Sys::OS::Check::get_strict_centos_version
was removed in version 98 in favor of Cpanel::OS.  This updates the
Imunify360 assessor to use Cpanel::OS.
Changelog:  Use Cpanel::OS instead of Cpanel::Sys::OS::Check::get_strict_centos_version

Use Cpanel::OS instead of Cpanel::Sys::OS::Check::get_strict_centos_version

---

pkg/Cpanel/Security/Advisor/Assessors/Mysql.pm

Case CPANEL-37936: In order to verify that the MySQL port was blocked in
the firewall, we would check that it was blocked for both IPv4 and IPv6
addresses.  However, this could result in us giving bad advice in the
event that IPv6 was disabled in the kernel since there would be no need
to block the MySQL port for IPv6 in that instance.  This change ensures
that IPv6 is enabled as part of the firewall check.
Changelog: Check IPv6 status as part of firewall check

Check IPv6 status as part of firewall check

---

pkg/Cpanel/Security/Advisor/Assessors/Apache.pm

Case CPANEL-38112: Removed usage of Cpanel::GenSysInfo for what appears
to have been a crufty variable.
Changelog:

Removed usage of deprecated Cpanel::GenSysInfo

---

pkg/Cpanel/Security/Advisor/Assessors.pm
pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm
t/pkg-Cpanel-Security-Advisor-Assessors-Imunify360.t
t/pkg-Cpanel-Security-Advisor-Assessors-Kernel.t
t/pkg-Cpanel-Security-Advisor-Assessors-Mysql.t
t/pkg-Cpanel-Security-Advisor-Assessors-Processes.t

Case CPANEL-34196: When ImunifyAV (free version) was added to
the product, the Security Advisor was updated to check whether
ClamAV was also installed, and if so, recommend removing it on
the grounds that it would be redundant. ClamAV is not redundant,
however, because it is still required for a setting in WHM that
enables scanning messages that pass through Exim. Instead of plainly
recommending ClamAV's removal, we should add some detail on why it
might (or might not) still be necessary.
This change also updates the RPM check for compatibility with versions
98 and up, which no longer have the Cpanel::RPM module, and fixes
several broken unit tests.

Adjust notice about removal of ClamAV when ImunifyAV is installed.

---

pkg/Cpanel/Security/Advisor/Assessors/Imunify360.pm
t/pkg-Cpanel-Security-Advisor-Assessors-Imunify360.t

Case CPANEL-37357: Ensure that ImunifyAV+ advice is offered when
Imunify360 is disabled in Manage2. Previously ImunifyAV+ would be
skipped if the i360 object attribute was not initialized, which would
happen when Imunify360 was disabled entirely.

Fix ImunifyAV+ advice when Imunify360 is disabled

---

pkg/Cpanel/Security/Advisor/Assessors/Jail.pm

Case CPANEL-38630: The jailshell check was generating an undefined
subroutine error on versions 100 and greater due to it's using '>=' for
version comparisons. This change addresses that by switching it to use
Cpanel::Version::compare().
Changelog:

Use Cpanel::Version::compare() for version comparison.

---

pkg/Cpanel/Security/Advisor/Assessors/Processes.pm

Case CPANEL-38802: Versions of cPanel that pre-date the Cpanel::OS
refactor were generating uninitialized value warnings due to the absence
of $Cpanel::OS::VERSION. This change addresses that by defaulting to 0
when undefined.
Changelog: Avoid uninitialized value warning on systems with legacy
Cpanel::OS

Avoid uninitialized value warning on legacy Cpanel OS Check
